Run session if any session is present
micro-ROS/rmw_microxrcedds pull request #305
Opened 2023-07-25 13:42 UTC by Acuadros95

Spin is not waiting if a session only haves timers, ending in a 100% CPU usage with code like this one: [int32_publisher](https://github.com/micro-ROS/micro-ROS-demos/blob/iron/rclc/int32_publisher/main.c).

Also, we should run all sessions atleast once, to ensure a response to incoming data (From Hard liveliness check for example).

Related issue: https://github.com/micro-ROS/rmw_microxrcedds/issues/297

2023-07-25 14:35 UTC, Acuadros95 commented
@mergify backport humble iron

2026-08-30 06:52 UTC, fallenmi requested changes
This review was prepared with OpenAI Codex assistance under the account owner's authorization.

The new [blocking fallback](https://github.com/micro-ROS/rmw_microxrcedds/blob/52f23f9a342ca35006325691a3d6cfe05ff8345f/rmw_microxrcedds_c/src/rmw_wait.c#L114-L125) runs before guard conditions are inspected. Guard conditions do not mark an XRCE context as `need_to_be_ran`, so a wait set containing an already-triggered guard enters this branch whenever a session exists. `uxr_run_session_timeout()` is then given the full per-session timeout, and `hasTriggered` is not checked until after that call returns. With an infinite RMW timeout, this can wait indefinitely for unrelated XRCE traffic. `rmw_trigger_guard_condition()` only sets the flag, so a guard raised while this fallback is blocked cannot interrupt it either.

I compiled the exact production `rmw_wait.c` from the PR merge-base, exact head, current `rolling`, and GitHub's synthetic current merge against a deterministic session/guard oracle. With one session, an already-triggered guard, and a 5-second wait:

- merge-base `6833232797d1034860125e949f34067a850eeb43` and current `rolling` `b6e02669d42fd5aeddc1e5b71bac65afd76cddf7` returned `RMW_RET_OK` after requesting a `0 ms` session run;
- exact head `52f23f9a342ca35006325691a3d6cfe05ff8345f` and synthetic merge `1fce9ed4782d8c4892cb20d7e1f45cac37446061` still returned `RMW_RET_OK`, but only after requesting a `5000 ms` session run.

The existing guard-condition test checks only the eventual return code, so it does not catch this latency regression. Please preserve immediate guard delivery when adding the timer-only blocking behavior, and add a timing/wakeup regression for both a pre-triggered guard and a guard triggered during the wait.

2026-09-09 10:45 UTC, EugenioCollado approved these changes

2026-09-09 11:28 UTC, merged

2026-09-23 10:38 UTC, David-LP99 commented
@mergify backport kilted jazzy

2026-09-23 12:24 UTC, David-LP99 commented
@mergify backport humble